// Code generated by entc, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"
	"wynn-member-api/ent"
)

// The AccessTokenFunc type is an adapter to allow the use of ordinary
// function as AccessToken mutator.
type AccessTokenFunc func(context.Context, *ent.AccessTokenMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AccessTokenFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.AccessTokenMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AccessTokenMutation", m)
	}
	return f(ctx, mv)
}

// The BankFunc type is an adapter to allow the use of ordinary
// function as Bank mutator.
type BankFunc func(context.Context, *ent.BankMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BankFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.BankMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BankMutation", m)
	}
	return f(ctx, mv)
}

// The BankAccountFunc type is an adapter to allow the use of ordinary
// function as BankAccount mutator.
type BankAccountFunc func(context.Context, *ent.BankAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BankAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.BankAccountMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BankAccountMutation", m)
	}
	return f(ctx, mv)
}

// The ChannelFunc type is an adapter to allow the use of ordinary
// function as Channel mutator.
type ChannelFunc func(context.Context, *ent.ChannelMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ChannelFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.ChannelMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ChannelMutation", m)
	}
	return f(ctx, mv)
}

// The GameFunc type is an adapter to allow the use of ordinary
// function as Game mutator.
type GameFunc func(context.Context, *ent.GameMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.GameMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameMutation", m)
	}
	return f(ctx, mv)
}

// The GameAccountFunc type is an adapter to allow the use of ordinary
// function as GameAccount mutator.
type GameAccountFunc func(context.Context, *ent.GameAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.GameAccountMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameAccountMutation", m)
	}
	return f(ctx, mv)
}

// The LineAccountFunc type is an adapter to allow the use of ordinary
// function as LineAccount mutator.
type LineAccountFunc func(context.Context, *ent.LineAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LineAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.LineAccountMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LineAccountMutation", m)
	}
	return f(ctx, mv)
}

// The MasterWalletTransactionFunc type is an adapter to allow the use of ordinary
// function as MasterWalletTransaction mutator.
type MasterWalletTransactionFunc func(context.Context, *ent.MasterWalletTransactionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MasterWalletTransactionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.MasterWalletTransactionMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MasterWalletTransactionMutation", m)
	}
	return f(ctx, mv)
}

// The PgSlotAccountFunc type is an adapter to allow the use of ordinary
// function as PgSlotAccount mutator.
type PgSlotAccountFunc func(context.Context, *ent.PgSlotAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PgSlotAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.PgSlotAccountMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PgSlotAccountMutation", m)
	}
	return f(ctx, mv)
}

// The PrettyGameAccountFunc type is an adapter to allow the use of ordinary
// function as PrettyGameAccount mutator.
type PrettyGameAccountFunc func(context.Context, *ent.PrettyGameAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PrettyGameAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.PrettyGameAccountMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PrettyGameAccountMutation", m)
	}
	return f(ctx, mv)
}

// The SAGameAccountFunc type is an adapter to allow the use of ordinary
// function as SAGameAccount mutator.
type SAGameAccountFunc func(context.Context, *ent.SAGameAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SAGameAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.SAGameAccountMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SAGameAccountMutation", m)
	}
	return f(ctx, mv)
}

// The TransferTransactionFunc type is an adapter to allow the use of ordinary
// function as TransferTransaction mutator.
type TransferTransactionFunc func(context.Context, *ent.TransferTransactionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TransferTransactionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.TransferTransactionMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TransferTransactionMutation", m)
	}
	return f(ctx, mv)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.UserMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
	}
	return f(ctx, mv)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
//
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
//
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
//
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
//
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
