// Code generated by entc, DO NOT EDIT.

package prettygameaccount

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the prettygameaccount type in the database.
	Label = "pretty_game_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldDesktopURI holds the string denoting the desktop_uri field in the database.
	FieldDesktopURI = "desktop_uri"
	// FieldMobileURI holds the string denoting the mobile_uri field in the database.
	FieldMobileURI = "mobile_uri"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRawData holds the string denoting the raw_data field in the database.
	FieldRawData = "raw_data"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the prettygameaccount in the database.
	Table = "pretty_game_accounts"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "pretty_game_accounts"
	// OwnerInverseTable is the table name for the GameAccount entity.
	// It exists in this package in order to avoid circular dependency with the "gameaccount" package.
	OwnerInverseTable = "game_accounts"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "game_account_pretty"
)

// Columns holds all SQL columns for prettygameaccount fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldUsername,
	FieldPassword,
	FieldDesktopURI,
	FieldMobileURI,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRawData,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pretty_game_accounts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"game_account_pretty",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUUID holds the default value on creation for the "uuid" field.
	DefaultUUID func() uuid.UUID
	// DesktopURIValidator is a validator for the "desktop_uri" field. It is called by the builders before save.
	DesktopURIValidator func(string) error
	// MobileURIValidator is a validator for the "mobile_uri" field. It is called by the builders before save.
	MobileURIValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
