// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"wynn-member-api/ent/accesstoken"
	"wynn-member-api/ent/predicate"
	"wynn-member-api/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessTokenQuery is the builder for querying AccessToken entities.
type AccessTokenQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AccessToken
	// eager-loading edges.
	withOwner *UserQuery
	withFKs   bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccessTokenQuery builder.
func (atq *AccessTokenQuery) Where(ps ...predicate.AccessToken) *AccessTokenQuery {
	atq.predicates = append(atq.predicates, ps...)
	return atq
}

// Limit adds a limit step to the query.
func (atq *AccessTokenQuery) Limit(limit int) *AccessTokenQuery {
	atq.limit = &limit
	return atq
}

// Offset adds an offset step to the query.
func (atq *AccessTokenQuery) Offset(offset int) *AccessTokenQuery {
	atq.offset = &offset
	return atq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (atq *AccessTokenQuery) Unique(unique bool) *AccessTokenQuery {
	atq.unique = &unique
	return atq
}

// Order adds an order step to the query.
func (atq *AccessTokenQuery) Order(o ...OrderFunc) *AccessTokenQuery {
	atq.order = append(atq.order, o...)
	return atq
}

// QueryOwner chains the current query on the "owner" edge.
func (atq *AccessTokenQuery) QueryOwner() *UserQuery {
	query := &UserQuery{config: atq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := atq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesstoken.Table, accesstoken.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accesstoken.OwnerTable, accesstoken.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(atq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccessToken entity from the query.
// Returns a *NotFoundError when no AccessToken was found.
func (atq *AccessTokenQuery) First(ctx context.Context) (*AccessToken, error) {
	nodes, err := atq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accesstoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (atq *AccessTokenQuery) FirstX(ctx context.Context) *AccessToken {
	node, err := atq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccessToken ID from the query.
// Returns a *NotFoundError when no AccessToken ID was found.
func (atq *AccessTokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = atq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accesstoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (atq *AccessTokenQuery) FirstIDX(ctx context.Context) int {
	id, err := atq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccessToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AccessToken entity is not found.
// Returns a *NotFoundError when no AccessToken entities are found.
func (atq *AccessTokenQuery) Only(ctx context.Context) (*AccessToken, error) {
	nodes, err := atq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accesstoken.Label}
	default:
		return nil, &NotSingularError{accesstoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (atq *AccessTokenQuery) OnlyX(ctx context.Context) *AccessToken {
	node, err := atq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccessToken ID in the query.
// Returns a *NotSingularError when exactly one AccessToken ID is not found.
// Returns a *NotFoundError when no entities are found.
func (atq *AccessTokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = atq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accesstoken.Label}
	default:
		err = &NotSingularError{accesstoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (atq *AccessTokenQuery) OnlyIDX(ctx context.Context) int {
	id, err := atq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccessTokens.
func (atq *AccessTokenQuery) All(ctx context.Context) ([]*AccessToken, error) {
	if err := atq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return atq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (atq *AccessTokenQuery) AllX(ctx context.Context) []*AccessToken {
	nodes, err := atq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccessToken IDs.
func (atq *AccessTokenQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := atq.Select(accesstoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (atq *AccessTokenQuery) IDsX(ctx context.Context) []int {
	ids, err := atq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (atq *AccessTokenQuery) Count(ctx context.Context) (int, error) {
	if err := atq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return atq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (atq *AccessTokenQuery) CountX(ctx context.Context) int {
	count, err := atq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (atq *AccessTokenQuery) Exist(ctx context.Context) (bool, error) {
	if err := atq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return atq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (atq *AccessTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := atq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccessTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (atq *AccessTokenQuery) Clone() *AccessTokenQuery {
	if atq == nil {
		return nil
	}
	return &AccessTokenQuery{
		config:     atq.config,
		limit:      atq.limit,
		offset:     atq.offset,
		order:      append([]OrderFunc{}, atq.order...),
		predicates: append([]predicate.AccessToken{}, atq.predicates...),
		withOwner:  atq.withOwner.Clone(),
		// clone intermediate query.
		sql:  atq.sql.Clone(),
		path: atq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (atq *AccessTokenQuery) WithOwner(opts ...func(*UserQuery)) *AccessTokenQuery {
	query := &UserQuery{config: atq.config}
	for _, opt := range opts {
		opt(query)
	}
	atq.withOwner = query
	return atq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LineToken string `json:"line_token,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccessToken.Query().
//		GroupBy(accesstoken.FieldLineToken).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (atq *AccessTokenQuery) GroupBy(field string, fields ...string) *AccessTokenGroupBy {
	group := &AccessTokenGroupBy{config: atq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return atq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LineToken string `json:"line_token,omitempty"`
//	}
//
//	client.AccessToken.Query().
//		Select(accesstoken.FieldLineToken).
//		Scan(ctx, &v)
//
func (atq *AccessTokenQuery) Select(fields ...string) *AccessTokenSelect {
	atq.fields = append(atq.fields, fields...)
	return &AccessTokenSelect{AccessTokenQuery: atq}
}

func (atq *AccessTokenQuery) prepareQuery(ctx context.Context) error {
	for _, f := range atq.fields {
		if !accesstoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if atq.path != nil {
		prev, err := atq.path(ctx)
		if err != nil {
			return err
		}
		atq.sql = prev
	}
	return nil
}

func (atq *AccessTokenQuery) sqlAll(ctx context.Context) ([]*AccessToken, error) {
	var (
		nodes       = []*AccessToken{}
		withFKs     = atq.withFKs
		_spec       = atq.querySpec()
		loadedTypes = [1]bool{
			atq.withOwner != nil,
		}
	)
	if atq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, accesstoken.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AccessToken{config: atq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, atq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := atq.withOwner; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*AccessToken)
		for i := range nodes {
			if nodes[i].user_access_token == nil {
				continue
			}
			fk := *nodes[i].user_access_token
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_access_token" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Owner = n
			}
		}
	}

	return nodes, nil
}

func (atq *AccessTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := atq.querySpec()
	return sqlgraph.CountNodes(ctx, atq.driver, _spec)
}

func (atq *AccessTokenQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := atq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (atq *AccessTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accesstoken.Table,
			Columns: accesstoken.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accesstoken.FieldID,
			},
		},
		From:   atq.sql,
		Unique: true,
	}
	if unique := atq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := atq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesstoken.FieldID)
		for i := range fields {
			if fields[i] != accesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := atq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := atq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := atq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := atq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (atq *AccessTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(atq.driver.Dialect())
	t1 := builder.Table(accesstoken.Table)
	columns := atq.fields
	if len(columns) == 0 {
		columns = accesstoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if atq.sql != nil {
		selector = atq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range atq.predicates {
		p(selector)
	}
	for _, p := range atq.order {
		p(selector)
	}
	if offset := atq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := atq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccessTokenGroupBy is the group-by builder for AccessToken entities.
type AccessTokenGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (atgb *AccessTokenGroupBy) Aggregate(fns ...AggregateFunc) *AccessTokenGroupBy {
	atgb.fns = append(atgb.fns, fns...)
	return atgb
}

// Scan applies the group-by query and scans the result into the given value.
func (atgb *AccessTokenGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := atgb.path(ctx)
	if err != nil {
		return err
	}
	atgb.sql = query
	return atgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (atgb *AccessTokenGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := atgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (atgb *AccessTokenGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: AccessTokenGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (atgb *AccessTokenGroupBy) StringsX(ctx context.Context) []string {
	v, err := atgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (atgb *AccessTokenGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = atgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesstoken.Label}
	default:
		err = fmt.Errorf("ent: AccessTokenGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (atgb *AccessTokenGroupBy) StringX(ctx context.Context) string {
	v, err := atgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (atgb *AccessTokenGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: AccessTokenGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (atgb *AccessTokenGroupBy) IntsX(ctx context.Context) []int {
	v, err := atgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (atgb *AccessTokenGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = atgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesstoken.Label}
	default:
		err = fmt.Errorf("ent: AccessTokenGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (atgb *AccessTokenGroupBy) IntX(ctx context.Context) int {
	v, err := atgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (atgb *AccessTokenGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: AccessTokenGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (atgb *AccessTokenGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := atgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (atgb *AccessTokenGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = atgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesstoken.Label}
	default:
		err = fmt.Errorf("ent: AccessTokenGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (atgb *AccessTokenGroupBy) Float64X(ctx context.Context) float64 {
	v, err := atgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (atgb *AccessTokenGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: AccessTokenGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (atgb *AccessTokenGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := atgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (atgb *AccessTokenGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = atgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesstoken.Label}
	default:
		err = fmt.Errorf("ent: AccessTokenGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (atgb *AccessTokenGroupBy) BoolX(ctx context.Context) bool {
	v, err := atgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (atgb *AccessTokenGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range atgb.fields {
		if !accesstoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := atgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := atgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (atgb *AccessTokenGroupBy) sqlQuery() *sql.Selector {
	selector := atgb.sql.Select()
	aggregation := make([]string, 0, len(atgb.fns))
	for _, fn := range atgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(atgb.fields)+len(atgb.fns))
		for _, f := range atgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(atgb.fields...)...)
}

// AccessTokenSelect is the builder for selecting fields of AccessToken entities.
type AccessTokenSelect struct {
	*AccessTokenQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ats *AccessTokenSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ats.prepareQuery(ctx); err != nil {
		return err
	}
	ats.sql = ats.AccessTokenQuery.sqlQuery(ctx)
	return ats.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ats *AccessTokenSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ats.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ats *AccessTokenSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: AccessTokenSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ats *AccessTokenSelect) StringsX(ctx context.Context) []string {
	v, err := ats.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ats *AccessTokenSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ats.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesstoken.Label}
	default:
		err = fmt.Errorf("ent: AccessTokenSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ats *AccessTokenSelect) StringX(ctx context.Context) string {
	v, err := ats.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ats *AccessTokenSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: AccessTokenSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ats *AccessTokenSelect) IntsX(ctx context.Context) []int {
	v, err := ats.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ats *AccessTokenSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ats.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesstoken.Label}
	default:
		err = fmt.Errorf("ent: AccessTokenSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ats *AccessTokenSelect) IntX(ctx context.Context) int {
	v, err := ats.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ats *AccessTokenSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: AccessTokenSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ats *AccessTokenSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ats.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ats *AccessTokenSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ats.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesstoken.Label}
	default:
		err = fmt.Errorf("ent: AccessTokenSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ats *AccessTokenSelect) Float64X(ctx context.Context) float64 {
	v, err := ats.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ats *AccessTokenSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: AccessTokenSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ats *AccessTokenSelect) BoolsX(ctx context.Context) []bool {
	v, err := ats.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ats *AccessTokenSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ats.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesstoken.Label}
	default:
		err = fmt.Errorf("ent: AccessTokenSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ats *AccessTokenSelect) BoolX(ctx context.Context) bool {
	v, err := ats.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ats *AccessTokenSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ats.sql.Query()
	if err := ats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
