// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"wynn-member-api/ent/lineaccount"
	"wynn-member-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineAccountDelete is the builder for deleting a LineAccount entity.
type LineAccountDelete struct {
	config
	hooks    []Hook
	mutation *LineAccountMutation
}

// Where appends a list predicates to the LineAccountDelete builder.
func (lad *LineAccountDelete) Where(ps ...predicate.LineAccount) *LineAccountDelete {
	lad.mutation.Where(ps...)
	return lad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lad *LineAccountDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lad.hooks) == 0 {
		affected, err = lad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LineAccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lad.mutation = mutation
			affected, err = lad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lad.hooks) - 1; i >= 0; i-- {
			if lad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lad *LineAccountDelete) ExecX(ctx context.Context) int {
	n, err := lad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lad *LineAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: lineaccount.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lineaccount.FieldID,
			},
		},
	}
	if ps := lad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, lad.driver, _spec)
}

// LineAccountDeleteOne is the builder for deleting a single LineAccount entity.
type LineAccountDeleteOne struct {
	lad *LineAccountDelete
}

// Exec executes the deletion query.
func (lado *LineAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := lado.lad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lineaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lado *LineAccountDeleteOne) ExecX(ctx context.Context) {
	lado.lad.ExecX(ctx)
}
