// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wynn-member-api/ent/gameaccount"
	"wynn-member-api/ent/pgslotaccount"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PgSlotAccountCreate is the builder for creating a PgSlotAccount entity.
type PgSlotAccountCreate struct {
	config
	mutation *PgSlotAccountMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (psac *PgSlotAccountCreate) SetUUID(u uuid.UUID) *PgSlotAccountCreate {
	psac.mutation.SetUUID(u)
	return psac
}

// SetUsername sets the "username" field.
func (psac *PgSlotAccountCreate) SetUsername(s string) *PgSlotAccountCreate {
	psac.mutation.SetUsername(s)
	return psac
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (psac *PgSlotAccountCreate) SetNillableUsername(s *string) *PgSlotAccountCreate {
	if s != nil {
		psac.SetUsername(*s)
	}
	return psac
}

// SetPassword sets the "password" field.
func (psac *PgSlotAccountCreate) SetPassword(s string) *PgSlotAccountCreate {
	psac.mutation.SetPassword(s)
	return psac
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (psac *PgSlotAccountCreate) SetNillablePassword(s *string) *PgSlotAccountCreate {
	if s != nil {
		psac.SetPassword(*s)
	}
	return psac
}

// SetDesktopURI sets the "desktop_uri" field.
func (psac *PgSlotAccountCreate) SetDesktopURI(s string) *PgSlotAccountCreate {
	psac.mutation.SetDesktopURI(s)
	return psac
}

// SetNillableDesktopURI sets the "desktop_uri" field if the given value is not nil.
func (psac *PgSlotAccountCreate) SetNillableDesktopURI(s *string) *PgSlotAccountCreate {
	if s != nil {
		psac.SetDesktopURI(*s)
	}
	return psac
}

// SetMobileURI sets the "mobile_uri" field.
func (psac *PgSlotAccountCreate) SetMobileURI(s string) *PgSlotAccountCreate {
	psac.mutation.SetMobileURI(s)
	return psac
}

// SetNillableMobileURI sets the "mobile_uri" field if the given value is not nil.
func (psac *PgSlotAccountCreate) SetNillableMobileURI(s *string) *PgSlotAccountCreate {
	if s != nil {
		psac.SetMobileURI(*s)
	}
	return psac
}

// SetCreatedAt sets the "created_at" field.
func (psac *PgSlotAccountCreate) SetCreatedAt(t time.Time) *PgSlotAccountCreate {
	psac.mutation.SetCreatedAt(t)
	return psac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (psac *PgSlotAccountCreate) SetNillableCreatedAt(t *time.Time) *PgSlotAccountCreate {
	if t != nil {
		psac.SetCreatedAt(*t)
	}
	return psac
}

// SetUpdatedAt sets the "updated_at" field.
func (psac *PgSlotAccountCreate) SetUpdatedAt(t time.Time) *PgSlotAccountCreate {
	psac.mutation.SetUpdatedAt(t)
	return psac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (psac *PgSlotAccountCreate) SetNillableUpdatedAt(t *time.Time) *PgSlotAccountCreate {
	if t != nil {
		psac.SetUpdatedAt(*t)
	}
	return psac
}

// SetRawData sets the "raw_data" field.
func (psac *PgSlotAccountCreate) SetRawData(s string) *PgSlotAccountCreate {
	psac.mutation.SetRawData(s)
	return psac
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (psac *PgSlotAccountCreate) SetNillableRawData(s *string) *PgSlotAccountCreate {
	if s != nil {
		psac.SetRawData(*s)
	}
	return psac
}

// SetOwnerID sets the "owner" edge to the GameAccount entity by ID.
func (psac *PgSlotAccountCreate) SetOwnerID(id int) *PgSlotAccountCreate {
	psac.mutation.SetOwnerID(id)
	return psac
}

// SetNillableOwnerID sets the "owner" edge to the GameAccount entity by ID if the given value is not nil.
func (psac *PgSlotAccountCreate) SetNillableOwnerID(id *int) *PgSlotAccountCreate {
	if id != nil {
		psac = psac.SetOwnerID(*id)
	}
	return psac
}

// SetOwner sets the "owner" edge to the GameAccount entity.
func (psac *PgSlotAccountCreate) SetOwner(g *GameAccount) *PgSlotAccountCreate {
	return psac.SetOwnerID(g.ID)
}

// Mutation returns the PgSlotAccountMutation object of the builder.
func (psac *PgSlotAccountCreate) Mutation() *PgSlotAccountMutation {
	return psac.mutation
}

// Save creates the PgSlotAccount in the database.
func (psac *PgSlotAccountCreate) Save(ctx context.Context) (*PgSlotAccount, error) {
	var (
		err  error
		node *PgSlotAccount
	)
	psac.defaults()
	if len(psac.hooks) == 0 {
		if err = psac.check(); err != nil {
			return nil, err
		}
		node, err = psac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PgSlotAccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = psac.check(); err != nil {
				return nil, err
			}
			psac.mutation = mutation
			if node, err = psac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(psac.hooks) - 1; i >= 0; i-- {
			if psac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = psac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, psac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (psac *PgSlotAccountCreate) SaveX(ctx context.Context) *PgSlotAccount {
	v, err := psac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (psac *PgSlotAccountCreate) Exec(ctx context.Context) error {
	_, err := psac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psac *PgSlotAccountCreate) ExecX(ctx context.Context) {
	if err := psac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psac *PgSlotAccountCreate) defaults() {
	if _, ok := psac.mutation.UUID(); !ok {
		v := pgslotaccount.DefaultUUID()
		psac.mutation.SetUUID(v)
	}
	if _, ok := psac.mutation.CreatedAt(); !ok {
		v := pgslotaccount.DefaultCreatedAt()
		psac.mutation.SetCreatedAt(v)
	}
	if _, ok := psac.mutation.UpdatedAt(); !ok {
		v := pgslotaccount.DefaultUpdatedAt()
		psac.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psac *PgSlotAccountCreate) check() error {
	if _, ok := psac.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "uuid"`)}
	}
	if v, ok := psac.mutation.DesktopURI(); ok {
		if err := pgslotaccount.DesktopURIValidator(v); err != nil {
			return &ValidationError{Name: "desktop_uri", err: fmt.Errorf(`ent: validator failed for field "desktop_uri": %w`, err)}
		}
	}
	if v, ok := psac.mutation.MobileURI(); ok {
		if err := pgslotaccount.MobileURIValidator(v); err != nil {
			return &ValidationError{Name: "mobile_uri", err: fmt.Errorf(`ent: validator failed for field "mobile_uri": %w`, err)}
		}
	}
	if _, ok := psac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := psac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	return nil
}

func (psac *PgSlotAccountCreate) sqlSave(ctx context.Context) (*PgSlotAccount, error) {
	_node, _spec := psac.createSpec()
	if err := sqlgraph.CreateNode(ctx, psac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (psac *PgSlotAccountCreate) createSpec() (*PgSlotAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &PgSlotAccount{config: psac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: pgslotaccount.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pgslotaccount.FieldID,
			},
		}
	)
	if value, ok := psac.mutation.UUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: pgslotaccount.FieldUUID,
		})
		_node.UUID = value
	}
	if value, ok := psac.mutation.Username(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pgslotaccount.FieldUsername,
		})
		_node.Username = value
	}
	if value, ok := psac.mutation.Password(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pgslotaccount.FieldPassword,
		})
		_node.Password = value
	}
	if value, ok := psac.mutation.DesktopURI(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pgslotaccount.FieldDesktopURI,
		})
		_node.DesktopURI = value
	}
	if value, ok := psac.mutation.MobileURI(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pgslotaccount.FieldMobileURI,
		})
		_node.MobileURI = value
	}
	if value, ok := psac.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pgslotaccount.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := psac.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pgslotaccount.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := psac.mutation.RawData(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pgslotaccount.FieldRawData,
		})
		_node.RawData = value
	}
	if nodes := psac.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pgslotaccount.OwnerTable,
			Columns: []string{pgslotaccount.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gameaccount.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.game_account_pgslot = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PgSlotAccountCreateBulk is the builder for creating many PgSlotAccount entities in bulk.
type PgSlotAccountCreateBulk struct {
	config
	builders []*PgSlotAccountCreate
}

// Save creates the PgSlotAccount entities in the database.
func (psacb *PgSlotAccountCreateBulk) Save(ctx context.Context) ([]*PgSlotAccount, error) {
	specs := make([]*sqlgraph.CreateSpec, len(psacb.builders))
	nodes := make([]*PgSlotAccount, len(psacb.builders))
	mutators := make([]Mutator, len(psacb.builders))
	for i := range psacb.builders {
		func(i int, root context.Context) {
			builder := psacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PgSlotAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, psacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, psacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, psacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (psacb *PgSlotAccountCreateBulk) SaveX(ctx context.Context) []*PgSlotAccount {
	v, err := psacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (psacb *PgSlotAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := psacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psacb *PgSlotAccountCreateBulk) ExecX(ctx context.Context) {
	if err := psacb.Exec(ctx); err != nil {
		panic(err)
	}
}
