// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"wynn-member-api/ent/gameaccount"
	"wynn-member-api/ent/predicate"
	"wynn-member-api/ent/prettygameaccount"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrettyGameAccountQuery is the builder for querying PrettyGameAccount entities.
type PrettyGameAccountQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PrettyGameAccount
	// eager-loading edges.
	withOwner *GameAccountQuery
	withFKs   bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PrettyGameAccountQuery builder.
func (pgaq *PrettyGameAccountQuery) Where(ps ...predicate.PrettyGameAccount) *PrettyGameAccountQuery {
	pgaq.predicates = append(pgaq.predicates, ps...)
	return pgaq
}

// Limit adds a limit step to the query.
func (pgaq *PrettyGameAccountQuery) Limit(limit int) *PrettyGameAccountQuery {
	pgaq.limit = &limit
	return pgaq
}

// Offset adds an offset step to the query.
func (pgaq *PrettyGameAccountQuery) Offset(offset int) *PrettyGameAccountQuery {
	pgaq.offset = &offset
	return pgaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pgaq *PrettyGameAccountQuery) Unique(unique bool) *PrettyGameAccountQuery {
	pgaq.unique = &unique
	return pgaq
}

// Order adds an order step to the query.
func (pgaq *PrettyGameAccountQuery) Order(o ...OrderFunc) *PrettyGameAccountQuery {
	pgaq.order = append(pgaq.order, o...)
	return pgaq
}

// QueryOwner chains the current query on the "owner" edge.
func (pgaq *PrettyGameAccountQuery) QueryOwner() *GameAccountQuery {
	query := &GameAccountQuery{config: pgaq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pgaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pgaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(prettygameaccount.Table, prettygameaccount.FieldID, selector),
			sqlgraph.To(gameaccount.Table, gameaccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, prettygameaccount.OwnerTable, prettygameaccount.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(pgaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PrettyGameAccount entity from the query.
// Returns a *NotFoundError when no PrettyGameAccount was found.
func (pgaq *PrettyGameAccountQuery) First(ctx context.Context) (*PrettyGameAccount, error) {
	nodes, err := pgaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{prettygameaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pgaq *PrettyGameAccountQuery) FirstX(ctx context.Context) *PrettyGameAccount {
	node, err := pgaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PrettyGameAccount ID from the query.
// Returns a *NotFoundError when no PrettyGameAccount ID was found.
func (pgaq *PrettyGameAccountQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pgaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{prettygameaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pgaq *PrettyGameAccountQuery) FirstIDX(ctx context.Context) int {
	id, err := pgaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PrettyGameAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one PrettyGameAccount entity is not found.
// Returns a *NotFoundError when no PrettyGameAccount entities are found.
func (pgaq *PrettyGameAccountQuery) Only(ctx context.Context) (*PrettyGameAccount, error) {
	nodes, err := pgaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{prettygameaccount.Label}
	default:
		return nil, &NotSingularError{prettygameaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pgaq *PrettyGameAccountQuery) OnlyX(ctx context.Context) *PrettyGameAccount {
	node, err := pgaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PrettyGameAccount ID in the query.
// Returns a *NotSingularError when exactly one PrettyGameAccount ID is not found.
// Returns a *NotFoundError when no entities are found.
func (pgaq *PrettyGameAccountQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pgaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{prettygameaccount.Label}
	default:
		err = &NotSingularError{prettygameaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pgaq *PrettyGameAccountQuery) OnlyIDX(ctx context.Context) int {
	id, err := pgaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PrettyGameAccounts.
func (pgaq *PrettyGameAccountQuery) All(ctx context.Context) ([]*PrettyGameAccount, error) {
	if err := pgaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pgaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pgaq *PrettyGameAccountQuery) AllX(ctx context.Context) []*PrettyGameAccount {
	nodes, err := pgaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PrettyGameAccount IDs.
func (pgaq *PrettyGameAccountQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pgaq.Select(prettygameaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pgaq *PrettyGameAccountQuery) IDsX(ctx context.Context) []int {
	ids, err := pgaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pgaq *PrettyGameAccountQuery) Count(ctx context.Context) (int, error) {
	if err := pgaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pgaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pgaq *PrettyGameAccountQuery) CountX(ctx context.Context) int {
	count, err := pgaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pgaq *PrettyGameAccountQuery) Exist(ctx context.Context) (bool, error) {
	if err := pgaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pgaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pgaq *PrettyGameAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := pgaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PrettyGameAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pgaq *PrettyGameAccountQuery) Clone() *PrettyGameAccountQuery {
	if pgaq == nil {
		return nil
	}
	return &PrettyGameAccountQuery{
		config:     pgaq.config,
		limit:      pgaq.limit,
		offset:     pgaq.offset,
		order:      append([]OrderFunc{}, pgaq.order...),
		predicates: append([]predicate.PrettyGameAccount{}, pgaq.predicates...),
		withOwner:  pgaq.withOwner.Clone(),
		// clone intermediate query.
		sql:  pgaq.sql.Clone(),
		path: pgaq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (pgaq *PrettyGameAccountQuery) WithOwner(opts ...func(*GameAccountQuery)) *PrettyGameAccountQuery {
	query := &GameAccountQuery{config: pgaq.config}
	for _, opt := range opts {
		opt(query)
	}
	pgaq.withOwner = query
	return pgaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PrettyGameAccount.Query().
//		GroupBy(prettygameaccount.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pgaq *PrettyGameAccountQuery) GroupBy(field string, fields ...string) *PrettyGameAccountGroupBy {
	group := &PrettyGameAccountGroupBy{config: pgaq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pgaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pgaq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.PrettyGameAccount.Query().
//		Select(prettygameaccount.FieldUUID).
//		Scan(ctx, &v)
//
func (pgaq *PrettyGameAccountQuery) Select(fields ...string) *PrettyGameAccountSelect {
	pgaq.fields = append(pgaq.fields, fields...)
	return &PrettyGameAccountSelect{PrettyGameAccountQuery: pgaq}
}

func (pgaq *PrettyGameAccountQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pgaq.fields {
		if !prettygameaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pgaq.path != nil {
		prev, err := pgaq.path(ctx)
		if err != nil {
			return err
		}
		pgaq.sql = prev
	}
	return nil
}

func (pgaq *PrettyGameAccountQuery) sqlAll(ctx context.Context) ([]*PrettyGameAccount, error) {
	var (
		nodes       = []*PrettyGameAccount{}
		withFKs     = pgaq.withFKs
		_spec       = pgaq.querySpec()
		loadedTypes = [1]bool{
			pgaq.withOwner != nil,
		}
	)
	if pgaq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, prettygameaccount.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &PrettyGameAccount{config: pgaq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, pgaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := pgaq.withOwner; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*PrettyGameAccount)
		for i := range nodes {
			if nodes[i].game_account_pretty == nil {
				continue
			}
			fk := *nodes[i].game_account_pretty
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(gameaccount.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "game_account_pretty" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Owner = n
			}
		}
	}

	return nodes, nil
}

func (pgaq *PrettyGameAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pgaq.querySpec()
	return sqlgraph.CountNodes(ctx, pgaq.driver, _spec)
}

func (pgaq *PrettyGameAccountQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pgaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pgaq *PrettyGameAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   prettygameaccount.Table,
			Columns: prettygameaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: prettygameaccount.FieldID,
			},
		},
		From:   pgaq.sql,
		Unique: true,
	}
	if unique := pgaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pgaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prettygameaccount.FieldID)
		for i := range fields {
			if fields[i] != prettygameaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pgaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pgaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pgaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pgaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pgaq *PrettyGameAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pgaq.driver.Dialect())
	t1 := builder.Table(prettygameaccount.Table)
	columns := pgaq.fields
	if len(columns) == 0 {
		columns = prettygameaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pgaq.sql != nil {
		selector = pgaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range pgaq.predicates {
		p(selector)
	}
	for _, p := range pgaq.order {
		p(selector)
	}
	if offset := pgaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pgaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PrettyGameAccountGroupBy is the group-by builder for PrettyGameAccount entities.
type PrettyGameAccountGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgagb *PrettyGameAccountGroupBy) Aggregate(fns ...AggregateFunc) *PrettyGameAccountGroupBy {
	pgagb.fns = append(pgagb.fns, fns...)
	return pgagb
}

// Scan applies the group-by query and scans the result into the given value.
func (pgagb *PrettyGameAccountGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pgagb.path(ctx)
	if err != nil {
		return err
	}
	pgagb.sql = query
	return pgagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pgagb *PrettyGameAccountGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pgagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pgagb *PrettyGameAccountGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pgagb.fields) > 1 {
		return nil, errors.New("ent: PrettyGameAccountGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pgagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pgagb *PrettyGameAccountGroupBy) StringsX(ctx context.Context) []string {
	v, err := pgagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pgagb *PrettyGameAccountGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pgagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{prettygameaccount.Label}
	default:
		err = fmt.Errorf("ent: PrettyGameAccountGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pgagb *PrettyGameAccountGroupBy) StringX(ctx context.Context) string {
	v, err := pgagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pgagb *PrettyGameAccountGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pgagb.fields) > 1 {
		return nil, errors.New("ent: PrettyGameAccountGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pgagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pgagb *PrettyGameAccountGroupBy) IntsX(ctx context.Context) []int {
	v, err := pgagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pgagb *PrettyGameAccountGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pgagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{prettygameaccount.Label}
	default:
		err = fmt.Errorf("ent: PrettyGameAccountGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pgagb *PrettyGameAccountGroupBy) IntX(ctx context.Context) int {
	v, err := pgagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pgagb *PrettyGameAccountGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pgagb.fields) > 1 {
		return nil, errors.New("ent: PrettyGameAccountGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pgagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pgagb *PrettyGameAccountGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pgagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pgagb *PrettyGameAccountGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pgagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{prettygameaccount.Label}
	default:
		err = fmt.Errorf("ent: PrettyGameAccountGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pgagb *PrettyGameAccountGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pgagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pgagb *PrettyGameAccountGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pgagb.fields) > 1 {
		return nil, errors.New("ent: PrettyGameAccountGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pgagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pgagb *PrettyGameAccountGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pgagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pgagb *PrettyGameAccountGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pgagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{prettygameaccount.Label}
	default:
		err = fmt.Errorf("ent: PrettyGameAccountGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pgagb *PrettyGameAccountGroupBy) BoolX(ctx context.Context) bool {
	v, err := pgagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pgagb *PrettyGameAccountGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pgagb.fields {
		if !prettygameaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pgagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pgagb *PrettyGameAccountGroupBy) sqlQuery() *sql.Selector {
	selector := pgagb.sql.Select()
	aggregation := make([]string, 0, len(pgagb.fns))
	for _, fn := range pgagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pgagb.fields)+len(pgagb.fns))
		for _, f := range pgagb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pgagb.fields...)...)
}

// PrettyGameAccountSelect is the builder for selecting fields of PrettyGameAccount entities.
type PrettyGameAccountSelect struct {
	*PrettyGameAccountQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pgas *PrettyGameAccountSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pgas.prepareQuery(ctx); err != nil {
		return err
	}
	pgas.sql = pgas.PrettyGameAccountQuery.sqlQuery(ctx)
	return pgas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pgas *PrettyGameAccountSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pgas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pgas *PrettyGameAccountSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pgas.fields) > 1 {
		return nil, errors.New("ent: PrettyGameAccountSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pgas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pgas *PrettyGameAccountSelect) StringsX(ctx context.Context) []string {
	v, err := pgas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pgas *PrettyGameAccountSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pgas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{prettygameaccount.Label}
	default:
		err = fmt.Errorf("ent: PrettyGameAccountSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pgas *PrettyGameAccountSelect) StringX(ctx context.Context) string {
	v, err := pgas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pgas *PrettyGameAccountSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pgas.fields) > 1 {
		return nil, errors.New("ent: PrettyGameAccountSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pgas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pgas *PrettyGameAccountSelect) IntsX(ctx context.Context) []int {
	v, err := pgas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pgas *PrettyGameAccountSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pgas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{prettygameaccount.Label}
	default:
		err = fmt.Errorf("ent: PrettyGameAccountSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pgas *PrettyGameAccountSelect) IntX(ctx context.Context) int {
	v, err := pgas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pgas *PrettyGameAccountSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pgas.fields) > 1 {
		return nil, errors.New("ent: PrettyGameAccountSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pgas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pgas *PrettyGameAccountSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pgas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pgas *PrettyGameAccountSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pgas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{prettygameaccount.Label}
	default:
		err = fmt.Errorf("ent: PrettyGameAccountSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pgas *PrettyGameAccountSelect) Float64X(ctx context.Context) float64 {
	v, err := pgas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pgas *PrettyGameAccountSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pgas.fields) > 1 {
		return nil, errors.New("ent: PrettyGameAccountSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pgas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pgas *PrettyGameAccountSelect) BoolsX(ctx context.Context) []bool {
	v, err := pgas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pgas *PrettyGameAccountSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pgas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{prettygameaccount.Label}
	default:
		err = fmt.Errorf("ent: PrettyGameAccountSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pgas *PrettyGameAccountSelect) BoolX(ctx context.Context) bool {
	v, err := pgas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pgas *PrettyGameAccountSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pgas.sql.Query()
	if err := pgas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
