// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"wynn-member-api/ent/gameaccount"
	"wynn-member-api/ent/predicate"
	"wynn-member-api/ent/sagameaccount"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SAGameAccountQuery is the builder for querying SAGameAccount entities.
type SAGameAccountQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.SAGameAccount
	// eager-loading edges.
	withOwner *GameAccountQuery
	withFKs   bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SAGameAccountQuery builder.
func (sgaq *SAGameAccountQuery) Where(ps ...predicate.SAGameAccount) *SAGameAccountQuery {
	sgaq.predicates = append(sgaq.predicates, ps...)
	return sgaq
}

// Limit adds a limit step to the query.
func (sgaq *SAGameAccountQuery) Limit(limit int) *SAGameAccountQuery {
	sgaq.limit = &limit
	return sgaq
}

// Offset adds an offset step to the query.
func (sgaq *SAGameAccountQuery) Offset(offset int) *SAGameAccountQuery {
	sgaq.offset = &offset
	return sgaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sgaq *SAGameAccountQuery) Unique(unique bool) *SAGameAccountQuery {
	sgaq.unique = &unique
	return sgaq
}

// Order adds an order step to the query.
func (sgaq *SAGameAccountQuery) Order(o ...OrderFunc) *SAGameAccountQuery {
	sgaq.order = append(sgaq.order, o...)
	return sgaq
}

// QueryOwner chains the current query on the "owner" edge.
func (sgaq *SAGameAccountQuery) QueryOwner() *GameAccountQuery {
	query := &GameAccountQuery{config: sgaq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sgaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sgaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sagameaccount.Table, sagameaccount.FieldID, selector),
			sqlgraph.To(gameaccount.Table, gameaccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sagameaccount.OwnerTable, sagameaccount.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(sgaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SAGameAccount entity from the query.
// Returns a *NotFoundError when no SAGameAccount was found.
func (sgaq *SAGameAccountQuery) First(ctx context.Context) (*SAGameAccount, error) {
	nodes, err := sgaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sagameaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sgaq *SAGameAccountQuery) FirstX(ctx context.Context) *SAGameAccount {
	node, err := sgaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SAGameAccount ID from the query.
// Returns a *NotFoundError when no SAGameAccount ID was found.
func (sgaq *SAGameAccountQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sgaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sagameaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sgaq *SAGameAccountQuery) FirstIDX(ctx context.Context) int {
	id, err := sgaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SAGameAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one SAGameAccount entity is not found.
// Returns a *NotFoundError when no SAGameAccount entities are found.
func (sgaq *SAGameAccountQuery) Only(ctx context.Context) (*SAGameAccount, error) {
	nodes, err := sgaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sagameaccount.Label}
	default:
		return nil, &NotSingularError{sagameaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sgaq *SAGameAccountQuery) OnlyX(ctx context.Context) *SAGameAccount {
	node, err := sgaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SAGameAccount ID in the query.
// Returns a *NotSingularError when exactly one SAGameAccount ID is not found.
// Returns a *NotFoundError when no entities are found.
func (sgaq *SAGameAccountQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sgaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sagameaccount.Label}
	default:
		err = &NotSingularError{sagameaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sgaq *SAGameAccountQuery) OnlyIDX(ctx context.Context) int {
	id, err := sgaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SAGameAccounts.
func (sgaq *SAGameAccountQuery) All(ctx context.Context) ([]*SAGameAccount, error) {
	if err := sgaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sgaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sgaq *SAGameAccountQuery) AllX(ctx context.Context) []*SAGameAccount {
	nodes, err := sgaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SAGameAccount IDs.
func (sgaq *SAGameAccountQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := sgaq.Select(sagameaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sgaq *SAGameAccountQuery) IDsX(ctx context.Context) []int {
	ids, err := sgaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sgaq *SAGameAccountQuery) Count(ctx context.Context) (int, error) {
	if err := sgaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sgaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sgaq *SAGameAccountQuery) CountX(ctx context.Context) int {
	count, err := sgaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sgaq *SAGameAccountQuery) Exist(ctx context.Context) (bool, error) {
	if err := sgaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sgaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sgaq *SAGameAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := sgaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SAGameAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sgaq *SAGameAccountQuery) Clone() *SAGameAccountQuery {
	if sgaq == nil {
		return nil
	}
	return &SAGameAccountQuery{
		config:     sgaq.config,
		limit:      sgaq.limit,
		offset:     sgaq.offset,
		order:      append([]OrderFunc{}, sgaq.order...),
		predicates: append([]predicate.SAGameAccount{}, sgaq.predicates...),
		withOwner:  sgaq.withOwner.Clone(),
		// clone intermediate query.
		sql:  sgaq.sql.Clone(),
		path: sgaq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (sgaq *SAGameAccountQuery) WithOwner(opts ...func(*GameAccountQuery)) *SAGameAccountQuery {
	query := &GameAccountQuery{config: sgaq.config}
	for _, opt := range opts {
		opt(query)
	}
	sgaq.withOwner = query
	return sgaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SAGameAccount.Query().
//		GroupBy(sagameaccount.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (sgaq *SAGameAccountQuery) GroupBy(field string, fields ...string) *SAGameAccountGroupBy {
	group := &SAGameAccountGroupBy{config: sgaq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sgaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sgaq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.SAGameAccount.Query().
//		Select(sagameaccount.FieldUUID).
//		Scan(ctx, &v)
//
func (sgaq *SAGameAccountQuery) Select(fields ...string) *SAGameAccountSelect {
	sgaq.fields = append(sgaq.fields, fields...)
	return &SAGameAccountSelect{SAGameAccountQuery: sgaq}
}

func (sgaq *SAGameAccountQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sgaq.fields {
		if !sagameaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sgaq.path != nil {
		prev, err := sgaq.path(ctx)
		if err != nil {
			return err
		}
		sgaq.sql = prev
	}
	return nil
}

func (sgaq *SAGameAccountQuery) sqlAll(ctx context.Context) ([]*SAGameAccount, error) {
	var (
		nodes       = []*SAGameAccount{}
		withFKs     = sgaq.withFKs
		_spec       = sgaq.querySpec()
		loadedTypes = [1]bool{
			sgaq.withOwner != nil,
		}
	)
	if sgaq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, sagameaccount.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &SAGameAccount{config: sgaq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, sgaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := sgaq.withOwner; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*SAGameAccount)
		for i := range nodes {
			if nodes[i].game_account_sagame == nil {
				continue
			}
			fk := *nodes[i].game_account_sagame
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(gameaccount.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "game_account_sagame" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Owner = n
			}
		}
	}

	return nodes, nil
}

func (sgaq *SAGameAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sgaq.querySpec()
	return sqlgraph.CountNodes(ctx, sgaq.driver, _spec)
}

func (sgaq *SAGameAccountQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sgaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sgaq *SAGameAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sagameaccount.Table,
			Columns: sagameaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sagameaccount.FieldID,
			},
		},
		From:   sgaq.sql,
		Unique: true,
	}
	if unique := sgaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sgaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sagameaccount.FieldID)
		for i := range fields {
			if fields[i] != sagameaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sgaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sgaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sgaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sgaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sgaq *SAGameAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sgaq.driver.Dialect())
	t1 := builder.Table(sagameaccount.Table)
	columns := sgaq.fields
	if len(columns) == 0 {
		columns = sagameaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sgaq.sql != nil {
		selector = sgaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range sgaq.predicates {
		p(selector)
	}
	for _, p := range sgaq.order {
		p(selector)
	}
	if offset := sgaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sgaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SAGameAccountGroupBy is the group-by builder for SAGameAccount entities.
type SAGameAccountGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgagb *SAGameAccountGroupBy) Aggregate(fns ...AggregateFunc) *SAGameAccountGroupBy {
	sgagb.fns = append(sgagb.fns, fns...)
	return sgagb
}

// Scan applies the group-by query and scans the result into the given value.
func (sgagb *SAGameAccountGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sgagb.path(ctx)
	if err != nil {
		return err
	}
	sgagb.sql = query
	return sgagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sgagb *SAGameAccountGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := sgagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (sgagb *SAGameAccountGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(sgagb.fields) > 1 {
		return nil, errors.New("ent: SAGameAccountGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := sgagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sgagb *SAGameAccountGroupBy) StringsX(ctx context.Context) []string {
	v, err := sgagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sgagb *SAGameAccountGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sgagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sagameaccount.Label}
	default:
		err = fmt.Errorf("ent: SAGameAccountGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sgagb *SAGameAccountGroupBy) StringX(ctx context.Context) string {
	v, err := sgagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (sgagb *SAGameAccountGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(sgagb.fields) > 1 {
		return nil, errors.New("ent: SAGameAccountGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := sgagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sgagb *SAGameAccountGroupBy) IntsX(ctx context.Context) []int {
	v, err := sgagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sgagb *SAGameAccountGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sgagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sagameaccount.Label}
	default:
		err = fmt.Errorf("ent: SAGameAccountGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sgagb *SAGameAccountGroupBy) IntX(ctx context.Context) int {
	v, err := sgagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (sgagb *SAGameAccountGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(sgagb.fields) > 1 {
		return nil, errors.New("ent: SAGameAccountGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := sgagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sgagb *SAGameAccountGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := sgagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sgagb *SAGameAccountGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sgagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sagameaccount.Label}
	default:
		err = fmt.Errorf("ent: SAGameAccountGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sgagb *SAGameAccountGroupBy) Float64X(ctx context.Context) float64 {
	v, err := sgagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (sgagb *SAGameAccountGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(sgagb.fields) > 1 {
		return nil, errors.New("ent: SAGameAccountGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := sgagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sgagb *SAGameAccountGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := sgagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sgagb *SAGameAccountGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sgagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sagameaccount.Label}
	default:
		err = fmt.Errorf("ent: SAGameAccountGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sgagb *SAGameAccountGroupBy) BoolX(ctx context.Context) bool {
	v, err := sgagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sgagb *SAGameAccountGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sgagb.fields {
		if !sagameaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sgagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sgagb *SAGameAccountGroupBy) sqlQuery() *sql.Selector {
	selector := sgagb.sql.Select()
	aggregation := make([]string, 0, len(sgagb.fns))
	for _, fn := range sgagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(sgagb.fields)+len(sgagb.fns))
		for _, f := range sgagb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(sgagb.fields...)...)
}

// SAGameAccountSelect is the builder for selecting fields of SAGameAccount entities.
type SAGameAccountSelect struct {
	*SAGameAccountQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sgas *SAGameAccountSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sgas.prepareQuery(ctx); err != nil {
		return err
	}
	sgas.sql = sgas.SAGameAccountQuery.sqlQuery(ctx)
	return sgas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sgas *SAGameAccountSelect) ScanX(ctx context.Context, v interface{}) {
	if err := sgas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (sgas *SAGameAccountSelect) Strings(ctx context.Context) ([]string, error) {
	if len(sgas.fields) > 1 {
		return nil, errors.New("ent: SAGameAccountSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := sgas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sgas *SAGameAccountSelect) StringsX(ctx context.Context) []string {
	v, err := sgas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (sgas *SAGameAccountSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sgas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sagameaccount.Label}
	default:
		err = fmt.Errorf("ent: SAGameAccountSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sgas *SAGameAccountSelect) StringX(ctx context.Context) string {
	v, err := sgas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (sgas *SAGameAccountSelect) Ints(ctx context.Context) ([]int, error) {
	if len(sgas.fields) > 1 {
		return nil, errors.New("ent: SAGameAccountSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := sgas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sgas *SAGameAccountSelect) IntsX(ctx context.Context) []int {
	v, err := sgas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (sgas *SAGameAccountSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sgas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sagameaccount.Label}
	default:
		err = fmt.Errorf("ent: SAGameAccountSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sgas *SAGameAccountSelect) IntX(ctx context.Context) int {
	v, err := sgas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (sgas *SAGameAccountSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(sgas.fields) > 1 {
		return nil, errors.New("ent: SAGameAccountSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := sgas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sgas *SAGameAccountSelect) Float64sX(ctx context.Context) []float64 {
	v, err := sgas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (sgas *SAGameAccountSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sgas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sagameaccount.Label}
	default:
		err = fmt.Errorf("ent: SAGameAccountSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sgas *SAGameAccountSelect) Float64X(ctx context.Context) float64 {
	v, err := sgas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (sgas *SAGameAccountSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(sgas.fields) > 1 {
		return nil, errors.New("ent: SAGameAccountSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := sgas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sgas *SAGameAccountSelect) BoolsX(ctx context.Context) []bool {
	v, err := sgas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (sgas *SAGameAccountSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sgas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sagameaccount.Label}
	default:
		err = fmt.Errorf("ent: SAGameAccountSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sgas *SAGameAccountSelect) BoolX(ctx context.Context) bool {
	v, err := sgas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sgas *SAGameAccountSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sgas.sql.Query()
	if err := sgas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
